### ISSUE TITLE
Cursor not turning into a hand when hovering over member links

### ISSUE THREAD

**Issue by cilliemalan** [RetroRabbit/rabbiteer-intern-project#29]
![image](https://cloud.githubusercontent.com/assets/3305301/10246132/b4381e0a-690e-11e5-941b-5931ea731ffd.png)

Probably need to add a style: 
```css
a:not([href]) {
    cursor: pointer;
}
```
